Controllers/CompanyController.cs
using InternshipForm.Data;
using InternshipForm.Models;
using InternshipForm.Service.Interface;
using InternshipForm.Views.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InternshipForm.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ApplicationDBContext _context;
            private readonly ICompanyService _companyService;



        public IActionResult AppliedStudent(int internshipId)
        {
            var appliedStudents = _companyService.GetAppliedStudents(internshipId);

            var personalInformationList = new List<PersonalInformation>();
            var createInternshipList = new List<CreateInternship>();    
            var appliedStudent = new List<AppliedInternships>();
            foreach( var student in appliedStudents)
            {
                personalInformationList.AddRange(student.PersonalInformation);
                createInternshipList.AddRange(student.CreateInternship);
                appliedStudent.AddRange(student.AppliedInternships);
            }
            var viewModel = new CompanyFormViewModel
            {
                PersonalInformation = personalInformationList,
                CreateInternship = createInternshipList,
                AppliedInternships = appliedStudent,
            };

            return View(viewModel);
        }


        public CompanyController(ApplicationDBContext context, ICompanyService companyService)
        {
            _context = context;
            _companyService = companyService;
        }



        public IActionResult Index()
        {
            return View();

        }

        public IActionResult UpdateApplicationStatus(int Id, string status)
        {
            if (status != null)
            {
                var student = _context.AppliedInternships.Find(Id);


                if (student != null)
                {
                    student.Status = status;
                    _context.SaveChanges();
                    TempData["Message"] = "Application status updated successfully";
                }
            }
            else
            {
                TempData["ErrorMessage"] = "Student not found";
            }

                return RedirectToAction("Index");
            }
        

        public IActionResult ViewCreatedInternship()
        {
            CreateInternship createInternship = new CreateInternship();
            List<CreateInternship> Internship= _context.CreateInternship.ToList();
            return View(Internship);
        }


      
        [HttpGet]
        public IActionResult CreateProfile(int Id)
        {
            CompanyProfile companyProfile = new CompanyProfile();
            return View(companyProfile);
        }
            [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateProfile(CompanyProfile company)
        {
            //if(ModelState.IsValid)
            {
                var result = _companyService.saveCreateCompanyProfile(company);
                return RedirectToAction("Index");
               
            }
            return View();
        }


        [HttpGet]
        public IActionResult CreateInternship()
        {
            CreateInternship model = new CreateInternship();
    

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateInternship(CreateInternship create)
        {
            var result = _companyService.saveCreateInternship(create);
            if (result != null) 
            {
                return RedirectToAction("CreatedInternship", new { Id = result});
            }
        
            return View();
        }
    }  
}




 

Controllers/StudentController.cs
using Azure.Core;
using InternshipForm.Data;
using InternshipForm.Models;
using InternshipForm.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Drawing;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.EntityFrameworkCore;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using static System.Net.Mime.MediaTypeNames;
using System.Security.Claims;
using InternshipForm.Service.Interface;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Microsoft.SqlServer.Server;
using InternshipForm.Views.ViewModel;


namespace InternshipForm.Controllers
{
    public class StudentController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly IStudentService _student;

        // creating the constructor for class form controller

        public StudentController(ApplicationDBContext context, IStudentService student)
        {
            _context = context;
            _student = student;
        }
        public IActionResult Index()
        {
            return View();
        }
        // controller action for student which they can view the applied internship has been shortlisted or rejected
        [HttpGet]
        public IActionResult ViewApplicationStatus()
        {
            // Assuming you have a way to retrieve data from your database or elsewhere
            var internships = _context.CreateInternship.ToList();
            var applications = _context.PersonalInformation.ToList();
            var appliedStudent = _context.AppliedInternships.ToList();

            var viewModel = new InternshipStatusViewModel
            {
                CreateInternship = internships,
                PersonalInformation = applications,
                AppliedInternships = appliedStudent,
                // Other properties initialization if needed
            };

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult GetApplicationStatus(int draw, int start, int length)
        {
            var query = (from ai in _context.AppliedInternships
                         join pi in _context.PersonalInformation on ai.RegisterUserId equals pi.RegisterUserId
                         join ci in _context.CreateInternship on ai.InternshipId equals ci.Id


                         select new
                         {
                              
                                 TitleOfInternship = ci.TitleOfInternship,
                                 NameOfCompany = ci.NameOfCompany,
                                 Address = ci.Address,
                                 Email = pi.Email,
                                 Status = ai.Status,
                                
                            
                         });
                                    


            // Count total records before applying pagination
            int recordsTotal = query.Count();

            // Apply pagination
            var data = query.Skip(start).Take(length).ToList();

            // Prepare the response
            var response = new
            {
                draw = draw,
                recordsTotal = recordsTotal,
                recordsFiltered = recordsTotal,

                data = data
            };

            return Json(response);
        }
    



        //controller for contact us
        [HttpGet]
        public IActionResult ContactUs()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ContactUs(ContactUs contactUs)
        {
            var result = _student.SaveContactUs(contactUs);
            return RedirectToAction("Index");
        }

        //view companies
        public IActionResult viewCompanyProfile()
        {
            List<CompanyProfile> companyProfiles = _context.CompanyProfile.ToList();
            return View(companyProfiles);
        }
        //View Internship
        public IActionResult ViewInternship(CreateInternship viewModel)
            {
            //CreateInternship createInternship = new CreateInternship();
            
            
            List<CreateInternship> Internship = _context.CreateInternship.ToList();
         
           
            return View(Internship);
            
            
        }
        public IActionResult GetInternshipForm(CreateInternship createInternship)
        {
          
            return View(createInternship);
        }



       
        [HttpGet]
        public IActionResult CreatePost()
        {
            InternshipFormViewModel model = new InternshipFormViewModel();
            model.Education = new List<Education> { new Education() };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePost(InternshipFormViewModel model)
        {
            if (ModelState.IsValid)
            {
               // var s = _student.saveStudentRecord();
                var personalinformation = _context.PersonalInformation.Add(model.PersonalInformation);
                _context.SaveChanges();
                // SQL code of education model
                foreach (var education in model.Education)
                {
                    education.InternId = personalinformation.Entity.InternId;
                    _context.Education.Add(education);
                }
                _context.SaveChanges();
                //sql code of guardian details model
                var guardiandetails = _context.GuardianDetails.Add(model.GuardianDetails);

                guardiandetails.Entity.InternId = personalinformation.Entity.InternId;
                _context.SaveChanges();
                //sql code of references model
                var references = _context.References.Add(model.References);
                references.Entity.InternId = personalinformation.Entity.InternId;
                _context.SaveChanges();

                return RedirectToAction("CreatePost");
            }

            return View(model);
        }
        //action method for create page 
        [HttpGet]
        public IActionResult Create(int? Id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            
           
                InternshipFormViewModel model = new InternshipFormViewModel();
            model.PersonalInformation = new PersonalInformation();
            model.Education = new List<Education> { new Education() };
            model.References = new References();
            model.OfficalUse = new OfficalUse();
            model.GuardianDetails = new GuardianDetails();
                if (Id.HasValue && Id.Value > 0)
            {
                model = _student.getStudentRecord(Id.Value);
            }
            
            return View(model);
        }

        public IActionResult Apply(int internshipId)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
          
            // Check if the user has already applied for this internship
            var appliedInternshipIds = _student.GetAppliedInternshipId(userId.Value).ToList();

            if (appliedInternshipIds.Contains(internshipId))
            {
                TempData["Message"] = "You have already applied for this Internship.";
                TempData["ShowMessage"] = true;
            }
            else
            {
                try
                {

                    InternshipFormViewModel model = new InternshipFormViewModel();
                    model.PersonalInformation = new PersonalInformation();
                    model.Education = new List<Education> { new Education() };
                    model.References = new References();
                    model.OfficalUse = new OfficalUse();
                    model.GuardianDetails = new GuardianDetails();
                    int internId = _student.GetInternId(userId.Value);
                    if (internId > 0)
                    {


                        // Add logic to store the application in the database
                        AppliedInternships application = new AppliedInternships();

                        application.RegisterUserId = userId.Value;
                        application.InternshipId = internshipId;
                        application.Status = "Pending";



                        _context.AppliedInternships.Add(application);

                        _context.SaveChanges();

                        TempData["Message"] = "You have successfully applied for this internship.";
                        TempData["ShowMessage"] = true;
                    }
                    else
                    {
                        return View("Create",model);
                    }
                }
                catch (Exception ex)
                {

                    TempData["Message"] = "An error occurred while applying for the internship.";
                    TempData["ShowMessage"] = true;

                }
            }

            return RedirectToAction("ViewInternship");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public IActionResult Create(InternshipFormViewModel model)
        {

            //if (ModelState.IsValid)
            {

                var userId = HttpContext.Session.GetInt32("UserId");
                model.PersonalInformation.RegisterUserId = userId.Value;
              
                var result = _student.saveStudentRecord(model);

                if(result > 0)
                {
                    return RedirectToAction("ViewInternship");
                }
               
              
            }
                return View(model);
            
        }

        
        //  action controller datatable

Views/Shared/AdminLTECompany/_Layout.cshtml
@{
    Layout = null;
}





<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IMS</title>

    <partial name="AdminLTECompany/_Styles" />
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <partial name="AdminLTECompany/_TopNavigation" />


        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <partial name="AdminLTECompany/_MainNavigation" />

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <partial name="AdminLTECompany/_Footer" />
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <partial name="AdminLTECompany/_Scripts" />
</body>
</html>

Views/Shared/AdminLTECompany/_MainNavigation.cshtml
@using InternshipForm.Helpers;


<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="~/Home" class="brand-link">
        @*  <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> *@
        <span class="brand-text font-weight-light"><strong>IMS</strong></span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
               @*  <a href="#" class="d-block">Laxmi Khanal</a> *@
            </div>
        </div>


        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>
        

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="true">
                <li class="nav-item ">
                    <a asp-controller="Company" asp-action="Index" class="nav-link @Url.MakeActiveClass("company","index")">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            Home
                        </p>
                    </a>
                </li>
                  <li class="nav-item ">
                <a asp-controller="Company" asp-action="ViewCreatedInternship" class="nav-link @Url.MakeActiveClass("home","privacy")">
                <i class="nav-icon fas fa-lock"></i>
                <p>
                Created Internships
                </p>
                </a>
                </li>  
                <li class="nav-item">
                    <a asp-controller="Company" asp-action="CreateProfile" class="nav-link @Url.MakeActiveClass("Company","CreateProfile")">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>
                            Create Profile 
                        </p>
                    </a>


                </li>
                 
                <li class="nav-item">
                    <a asp-controller="Company" asp-action="CreateInternship" class="nav-link @Url.MakeActiveClass("Company","CreateInternship")">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>
                            Create Internship
                        </p>
                    </a>


                </li>
                @* <li class="nav-item">
                    <a asp-controller="Company" asp-action="ViewCompanyProfile" class="nav-link @Url.MakeActiveClass("Company","ViewCompanyProfile")">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>
                            Profile
                        </p>
                    </a>


                </li>  *@
              @*   <li class="nav-item">
                    <a asp-controller="Company" asp-action="ViewCompanyProfile" asp-route-id="1017" class="nav-link">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>
                            Profile
                        </p>
                    </a>
                </li> *@

                

               @*  <li class="nav-item">
                    <a asp-controller="Student" asp-action="Create" class="nav-link @Url.MakeActiveClass("Student","Create")">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>
                            
                        </p>
                    </a>

                </li>
                <li class="nav-item">
                    <a asp-controller="Student" asp-action="Details" class="nav-link @Url.MakeActiveClass("Student","Details")">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>
                           
                        </p>
                    </a>


                </li> *@
               
    </div>
    <!-- /.sidebar -->
</aside>

Views/Shared/AdminLTECompany/_TopNavigation.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
        @*  <li class="nav-item d-none d-sm-inline-block">
        <a href="https://localhost:44356/RegisterUser/UserRegister" class="nav-link btn-primary"><strong>Sign In</strong></a>
        </li> *@
        @*    <li class="nav-item d-none d-sm-inline-block">
        <a href="https://localhost:44356/RegisterUser/UserLogin">Login</a>
        </li> *@
    </ul>
    @* // logout button for company *@

    <form method="post" asp-controller="RegisterUser" asp-action="CompanyLogout" style="text-align: right;">
        <input type="submit" value="Logout" style="background-color: red; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;" />
    </form>





    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>


                            </button>

                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>